# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
