# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_auto_20171109_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Web.Video'),
        ),
    ]
