# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_user_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image_url',
            field=models.TextField(default='null'),
        ),
    ]
