# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_video_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.TextField(default='02:30'),
        ),
    ]
